@extends('layouts.admin')
@section('title', 'ขั้นตอนการใช้งาน')
@push('styles')
<style>
    .tutorial-intro{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:22px}.tutorial-intro h1{font-size:24px;font-weight:700;margin:0 0 7px}.tutorial-intro p{color:#98a6b8;margin:0}.tutorial-count{color:#98a6b8;white-space:nowrap}.tutorial-filters{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:22px}.tutorial-filter{border:1px solid #eff0f5;background:#fff;color:#495057;border-radius:20px;padding:8px 14px}.tutorial-filter.active{background:#556ee6;border-color:#556ee6;color:#fff}.tutorial-search{max-width:360px;margin-left:auto}.tutorial-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.tutorial-card{background:#fff;border:1px solid #eff0f5;border-radius:12px;overflow:hidden;box-shadow:0 4px 12px rgba(31,45,61,.04)}.tutorial-thumb{height:126px;background:linear-gradient(135deg,#29243e,#11101b);display:flex;align-items:center;justify-content:center;color:#fff;position:relative}.tutorial-thumb:after{content:'▶';width:48px;height:48px;border-radius:50%;background:#fff;color:#556ee6;display:flex;align-items:center;justify-content:center;padding-left:3px}.tutorial-body{padding:15px}.tutorial-category{display:inline-flex;align-items:center;background:#f1f3f6;border-radius:16px;padding:4px 9px;font-size:11px;color:#697386;margin-bottom:10px}.tutorial-body h6{font-size:14px;line-height:1.5;margin:0;min-height:42px}.tutorial-action{display:block;margin-top:13px;text-align:center;text-decoration:none;border:1px solid #556ee6;color:#556ee6;border-radius:6px;padding:6px 10px;font-size:12px}.tutorial-action:hover{background:#556ee6;color:#fff}.tutorial-action.disabled{color:#98a6b8;border-color:#eff0f5;pointer-events:none}@media(max-width:991.98px){.tutorial-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:575.98px){.tutorial-intro{flex-direction:column}.tutorial-search{max-width:none;width:100%}.tutorial-grid{grid-template-columns:1fr}}
</style>
@endpush
@php
    $tutorials = [
        ['category'=>'เริ่มต้นใช้งาน','title'=>'ขั้นตอนการสมัครสมาชิก'], ['category'=>'ไลฟ์สด','title'=>'ขั้นตอนการเริ่มไลฟ์'], ['category'=>'ไลฟ์สด','title'=>'เพิ่มสินค้าด่วนหน้าไลฟ์'], ['category'=>'สินค้า','title'=>'สร้างรหัสหลายสี/ไซส์ สำหรับร้านมือ 1'], ['category'=>'สินค้า','title'=>'สร้างหลายรหัส ราคาเท่าๆกัน ร้านมือ 2'], ['category'=>'ขนส่ง & ใบปะหน้า','title'=>'สอนเชื่อม VIP ขนส่ง'], ['category'=>'ขนส่ง & ใบปะหน้า','title'=>'สอนปรินท์/ยกเลิกใบปะหน้า Book ขนส่งแฟลช'], ['category'=>'เชื่อมต่อ & สิทธิ์','title'=>'ตั้งค่าระบบดูด ส่งสรุปยอดผ่าน LINE OA'], ['category'=>'เชื่อมต่อ & สิทธิ์','title'=>'เพิ่มสิทธิ์ให้แอพ CFSHOPS'], ['category'=>'เชื่อมต่อ & สิทธิ์','title'=>'การแก้ไขเมื่อไม่เห็นเพจ ตอนสร้างร้านค้า'], ['category'=>'เชื่อมต่อ & สิทธิ์','title'=>'เพิ่มบัญชีอื่นให้มีสิทธิ์เข้าถึงเพจ Facebook'], ['category'=>'TikTok','title'=>'เชื่อมช่อง TikTok ของร้าน','url'=>'https://www.tiktok.com/@cf_shops/video/7410648998849137938'], ['category'=>'TikTok','title'=>'รับลิงก์เปิดระบบไปวางบน TikTok','url'=>'https://www.tiktok.com/@cf_shops/video/7407696398927383815'], ['category'=>'TikTok','title'=>'ปรับ TikTok เป็นบัญชีธุรกิจ','url'=>'https://www.tiktok.com/@cf_shops/video/7403689633881640209'], ['category'=>'TikTok','title'=>'ปิดกรองความคิดเห็น Tiktok Live','url'=>'https://www.tiktok.com/@cf_shops/video/7263732567873031442'], ['category'=>'TikTok','title'=>'เปิดแสดงลิงก์ Tiktok สำหรับร้านที่ลูกค้ามองไม่เห็นลิงก์'],
    ];
    $categoryCounts = collect($tutorials)->groupBy('category')->map->count();
@endphp
@section('content')
<div class="page-title-box"><h4 class="page-title mb-0">ขั้นตอนการใช้งาน</h4><div class="text-muted small mt-1">เมนูหลัก / ขั้นตอนการใช้งาน</div></div>
<section class="tutorial-intro"><div><h1>รวมวิดีโอสอนใช้งานระบบ CF Manager</h1><p>เรียนรู้ทุกขั้นตอน ตั้งแต่เริ่มใช้งาน จัดการสินค้า เชื่อมขนส่ง ไปจนถึง TikTok</p></div><div class="tutorial-count">{{ count($tutorials) }} วิดีโอ · {{ $categoryCounts->count() }} หมวด</div></section>
<div class="tutorial-filters"><button class="tutorial-filter active" type="button" data-filter="all">ทั้งหมด {{ count($tutorials) }}</button>@foreach($categoryCounts as $category => $count)<button class="tutorial-filter" type="button" data-filter="{{ $category }}">{{ $category }} {{ $count }}</button>@endforeach</div>
<div class="d-flex justify-content-end mb-3"><input class="form-control tutorial-search" id="tutorial-search" type="search" placeholder="ค้นหาวิดีโอ..."></div>
<div class="tutorial-grid" id="tutorial-grid">@foreach($tutorials as $tutorial)<article class="tutorial-card" data-category="{{ $tutorial['category'] }}" data-title="{{ $tutorial['title'] }}"><div class="tutorial-thumb"></div><div class="tutorial-body"><span class="tutorial-category">{{ $tutorial['category'] }}</span><h6>{{ $tutorial['title'] }}</h6>@if(!empty($tutorial['url']))<a class="tutorial-action" href="{{ $tutorial['url'] }}" target="_blank" rel="noopener">เปิดวิดีโอ</a>@else<button class="tutorial-action disabled" type="button" disabled>วิดีโอกำลังเตรียม</button>@endif</div></article>@endforeach</div>
@endsection
@push('scripts')
<script>(()=>{const buttons=document.querySelectorAll('[data-filter]'),cards=document.querySelectorAll('.tutorial-card'),search=document.getElementById('tutorial-search');let active='all';const render=()=>{const q=(search.value||'').toLowerCase();cards.forEach(card=>{card.style.display=(active==='all'||card.dataset.category===active)&&(!q||card.dataset.title.toLowerCase().includes(q))?'':'none';});};buttons.forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;buttons.forEach(item=>item.classList.toggle('active',item===button));render();}));search.addEventListener('input',render);})();</script>
@endpush
